/*
identifier	::=	[ :letter ]+ ;
type		::=	"int" | "char" | "ssize_t";
param		::=	type identifier;
func		::=	type identifier '(' [ param ]? [ ',' param ]* ')' ';' ;
*//* asdlfkjasdlfkj*/

ab(string a, string b) ::= "";

truc  ::= "g";
test		::=	ab truc;

/*
   .fail .return .rule
   0123456789abcd*/
